### ISSUE TITLE
4.3.5 적용 이후 crash 발생

### ISSUE THREAD

**Issue by KWONJAE** [naver/nam-sdk-android#12]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/naver/nam-sdk-android/issues)

### Version

4.3.5

### AGP Version

7.2.0

### Android version

all

### Device

all

### Steps to Reproduce

1. 4.3.5 적용된 샘플 앱 실행
2. `스마트 채널` 광고 선택
3. crash 발생

### Expected Result

crash가 발생하지 않아야 합니다.

### Actual Result

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.naver.gfpsdk.GfpAdMuteView" on path: DexPathList[[zip file "/data/app/~~nIzXmGi9SVqQ83yQWSrC4Q==/com.skmc.okcashbag.home_google-udiuNWU5Ly0HE5ZdHAyz7w==/base.apk"],nativeLibraryDirectories=[/data/app/~~nIzXmGi9SVqQ83yQWSrC4Q==/com.skmc.okcashbag.home_google-udiuNWU5Ly0HE5ZdHAyz7w==/lib/arm64, /data/app/~~nIzXmGi9SVqQ83yQWSrC4Q==/com.skmc.okcashbag.home_google-udiuNWU5Ly0HE5ZdHAyz7w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.naver.gfpsdk.provider.NdaNativeSimpleAdapter.preRequestAd(NdaNativeSimpleAdapter.kt:36) 
        at com.naver.gfpsdk.provider.GfpAdAdapter.internalRequestAd(SourceFile:4) 
        at com.naver.gfpsdk.provider.GfpNativeSimpleAdAdapter.requestAd(SourceFile:5) 
        at com.naver.gfpsdk.s.a(SourceFile:2) 
        at com.naver.gfpsdk.b.d(SourceFile:2) 
        at com.naver.gfpsdk.w.a(SourceFile:31) 
        at com.naver.gfpsdk.internal.m.z(SourceFile:54) 
        at com.naver.gfpsdk.internal.m.v(SourceFile:8) 
        at com.naver.gfpsdk.internal.m.a(SourceFile:85) 
        at com.naver.gfpsdk.internal.m$d.onResponse(SourceFile:1) 
        at com.naver.gfpsdk.internal.services.BaseCaller$a$a.a(SourceFile:23) 
        at com.naver.gfpsdk.internal.network.j.a(SourceFile:1) 
        at com.naver.gfpsdk.internal.network.j.b(SourceFile:2) 
        at com.naver.gfpsdk.internal.q$a$c.run(SourceFile:1) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:247) 
        at android.app.ActivityThread.main(ActivityThread.java:8656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 

```

**Comment by kwonjae-lee** [comment]
4.3.3 버전에서 내부 개선 사항이 있었는데요.
외부 참조 클래스에 난독화 설정이 되어 문제가 됐습니다.
수정 예정입니다.

**Comment by kwonjae-lee** [comment]
@zaphike 님 안녕하세요~
4.3.6 버전 업데이트로 대응 했습니다.
해당 버전으로 확인 부탁드리겠습니다 (__)
혹시 문제가 재연된다면 이슈 다시 열어주시면 감사하겠습니다!
