### ISSUE TITLE
SmartChannel 사용시 crash 발생

### ISSUE THREAD

**Issue by myung6024** [naver/nam-sdk-android#21]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/naver/nam-sdk-android/issues)

### Version

5.0.0

### AGP Version

7.0.3

### Android version

12

### Device

Galaxy Z Fold4

### Steps to Reproduce

Sample 앱과 동일한 코드를 이용하여 광고 노출을 구현하였습니다.

### Expected Result

정상적으로 광고가 노출되어야 합니다.

### Actual Result

```
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/naver/gfpsdk/r;
	at com.naver.gfpsdk.v.a(SourceFile:23)
	at com.naver.gfpsdk.internal.m.z(SourceFile:54)
	at com.naver.gfpsdk.internal.m.v(SourceFile:8)
	at com.naver.gfpsdk.internal.m.a(SourceFile:85)
	at com.naver.gfpsdk.internal.m$d.onResponse(SourceFile:1)
	at com.naver.gfpsdk.internal.services.BaseCaller$a$a.a(SourceFile:23)
	at com.naver.gfpsdk.internal.network.j.a(SourceFile:1)
	at com.naver.gfpsdk.internal.network.j.b(SourceFile:2)
	at com.naver.gfpsdk.internal.q$a$c.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.naver.gfpsdk.r" on path: DexPathList[[zip file "/data/app/~~QN8bfugiMoeswVf4E7yLjg==/9Ei7fZgVyuI-tkqBQEYFwA==/base.apk"],nativeLibraryDirectories=[/data/app/~~QN8bfugiMoeswVf4E7yLjg==/9Ei7fZgVyuI-tkqBQEYFwA==/lib/arm64, /data/app/~~QN8bfugiMoeswVf4E7yLjg==/9Ei7fZgVyuI-tkqBQEYFwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
      	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
      	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
      	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
      	at com.naver.gfpsdk.v.a(SourceFile:23) 
      	at com.naver.gfpsdk.internal.m.z(SourceFile:54) 
      	at com.naver.gfpsdk.internal.m.v(SourceFile:8) 
      	at com.naver.gfpsdk.internal.m.a(SourceFile:85) 
      	at com.naver.gfpsdk.internal.m$d.onResponse(SourceFile:1) 
      	at com.naver.gfpsdk.internal.services.BaseCaller$a$a.a(SourceFile:23) 
      	at com.naver.gfpsdk.internal.network.j.a(SourceFile:1) 
      	at com.naver.gfpsdk.internal.network.j.b(SourceFile:2) 
      	at com.naver.gfpsdk.internal.q$a$c.run(SourceFile:1) 
      	at android.os.Handler.handleCallback(Handler.java:942) 
      	at android.os.Handler.dispatchMessage(Handler.java:99) 
      	at android.os.Looper.loopOnce(Looper.java:201) 
      	at android.os.Looper.loop(Looper.java:288) 
      	at android.app.ActivityThread.main(ActivityThread.java:7898) 
      	at java.lang.reflect.Method.invoke(Native Method) 
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by kwonjae-lee** [comment]
@myung6024 불편을 드려 죄송합니다.
내부 빌드 중 난독화 과정에서 문제가 생겼습니다.
수정 후 다시 말씀드리겠습니다 (__)

**Comment by kwonjae-lee** [comment]
@myung6024 님 두가지 부탁드릴 부분이 있습니다.
저희 샘플 앱을 빌드 했을 때는 문제가 없다보니 양해 부탁드립니다.

- proguard 설정 파일에 아래 옵션을 추가해서 문제된 클래스 정보(`com.naver.gfpsdk.r`)를 확인 할 수 있을까요?
`-printmapping external-mapping.txt`
확인되면 다음 배포 때 난독화 되지 않도록 옵션 추가 하겠습니다.
- 그리고 아래 옵션을 사용하면 문제가 발생하지 않을 것 같은데요.
같이 확인 부탁드립니다.
`-keep class com.naver.gfpsdk.* { *; }`

감사합니다.

**Comment by myung6024** [comment]
안녕하세요. debug로 기능 테스트 중 크래시가 발생한 것이라 난독화가 적용되어 있지 않은 상태입니다.
혹시 짐작 가는 부분은 없으실까요? @kwonjae-lee

**Comment by kidoohan** [comment]
@myung6024 안녕하세요:)

혹시, nam sdk 의존성 설정하신 부분을 공유해주실 수 있을까요?

**Comment by myung6024** [comment]
```
    implementation platform('com.naver.gfpsdk:nam-bom:5.0.0')
    implementation 'com.naver.gfpsdk:nam-core'
    implementation 'com.naver.gfpsdk:nam-nda'
```
안녕하세요 위와 같이 설정하였습니다.

**Comment by kidoohan** [comment]
확인 감사합니다.
원인 파악이 안되고 있어서 그런데요. 두가지 정도 확인해주시면 감사하겠습니다:)

1. nam-core.aar 파일을 공유해주실 수 있을까요?  (aar 파일 첨부가 되지 않는다면 kidoo.han@navercorp.com 메일로 공유주시면 감사하겠습니다:))
2. debug 빌드에서는 minify 옵션을 걸지 않으신걸까요?

**Comment by kidoohan** [comment]
@myung6024 님 추가적으로 요청 드리고 싶은 부분이 있는데요...
가능하시다면 debug 빌드의 apk 파일도 같이 공유주시면 원인 파악에 도움이 될 듯 합니다:)

**Comment by myung6024** [comment]
debug에서는 minify옵션을 걸지 않았습니다.
그런데 오히려 minifyEnabled을 true로 하였을 때에는 해당 크래시가 발생하지 않고 정상 작동하며 false로 하면 같은 크래시가 발생합니다.
혹시 짐작가는 이유가 있으실까요? @kidoohan

**Comment by kidoohan** [comment]
그렇다면 multidex 상황에서 이슈가 생기는 것으로 보이네요. Minify 옵션을 설정하지 않은 상황에서 apk 파일 내 dex 파일 갯수는 2개 이상이신가요? 

내일 출근 이후에 좀 더 자세히 봐보고 공유드리겠습니다:)

문제가 발생하는 케이스에서의 apk 파일을 공유주시면 문제 해결에 큰 도움이 될 것 같습니다.

**Comment by kidoohan** [comment]
@myung6024 님 안녕하세요. 원활한 문제해결을 위해서 줌을 통해 화상으로 의견을 나누면 좋을 듯 한데요. 혹시 괜찮으실까요?

**Comment by myung6024** [comment]
넵 좋습니다

**Comment by kidoohan** [comment]
https://line.zoom.us/j/92553495149?pwd=eGRmbmJ1MWlaNnYyL0tpVXh2NlhTUT09 접속 가능하실까요?

**Comment by myung6024** [comment]
4.4.1에서도 같은 증상 발생합니다 @kidoohan

**Comment by kidoohan** [comment]
확인 감사합니다:) 
번거로우시겠지만 4.4.0 버전으로도 테스트 한번 더 가능하실까요?

**Comment by myung6024** [comment]
같은 증상 발생합니다 😢

**Comment by kidoohan** [comment]
@myung6024 님 크래시를 발생시켜주실 수 있을까요? 크래시 로그를 좀 더 파악해보고자 요청 드립니다.

**Comment by myung6024** [comment]
5.0.0에서 진행하면 될까요?

**Comment by kidoohan** [comment]
버전 관계없이 진행해주시면 감사하겠습니다. 추가 질문이 하나 있는데요. 제가 기억하기로는 에브리타임앱이 예전에는 리액트 네이티브로 만들어졌던 것으로 아는데요. 지금은 네이티브로 전환되어 있는거죠?

**Comment by myung6024** [comment]
처음부터 네이티브로 개발되었습니다!

**Comment by myung6024** [comment]
> 크래시 발생시 기존 앱 삭제후 재 빌드 및 설치 부탁드립니다:)

진행하였습니다!

**Comment by kidoohan** [comment]
@myung6024 님 혹시 몰라서 공유드리는데요. 아래 케이스 proguard 파일에 추가후 재시도 해주실 수 있을까요?

-dontwarn com.naver.gfpsdk.**
-keep class com.naver.gfpsdk.** {*; }
-keep interface com.naver.gfpsdk.** {*; }

**Comment by myung6024** [comment]
지금 진행해도 괜찮습니다!

**Comment by kidoohan** [comment]
https://line.zoom.us/j/92553495149?pwd=eGRmbmJ1MWlaNnYyL0tpVXh2NlhTUT09 로 접속 부탁드립니다:)

**Comment by kidoohan** [comment]
@myung6024 님 

https://naver.github.io/nam-sdk-guide/android/advanced/initialize_manually 가이드에 따라 Application#onCreate() 안에서 수동 초기화를 진행 후 테스트 해봐주실 수 있을까요?

**Comment by myung6024** [comment]
수동 초기화하여 `initializationResult.getMessage()`에서 `GFP SDK is initialized.` 내려주고 크래시 발생합니다.

**Comment by myung6024** [comment]
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'kotlin-kapt'

repositories {
    jcenter()
    mavenCentral()
    maven {
        url 'http://wordpress-mobile.github.io/Android-PasscodeLock'
        allowInsecureProtocol = true
    }
    maven {
        url 'http://chocl9.github.io'
        allowInsecureProtocol = true
    }
    maven {
        url 'http://devrepo.kakao.com:8088/nexus/content/groups/public'
        allowInsecureProtocol = true
    }
    maven {
        url 'http://chocl9.github.io'
        allowInsecureProtocol = true
    }
    maven { url "https://jitpack.io" }
    maven { url "https://maven.google.com" }
}

android {
    compileSdkVersion Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
    buildToolsVersion '31.0.0'

    defaultConfig {
        minSdkVersion Integer.parseInt(project.ANDROID_BUILD_MIN_SDK_VERSION)
        targetSdkVersion Integer.parseInt(project.ANDROID_BUILD_TARGET_SDK_VERSION)

        // Enabling multidex support.
        multiDexEnabled true

        applicationId "com.everytime.v2"
        resConfigs "en", "ko"
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    lintOptions {
        checkReleaseBuilds false
    }

    buildTypes {
        debug {
             ...
            debuggable true
        }
        release {
             ...
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            shrinkResources true
            minifyEnabled true
            ndk {
                debugSymbolLevel 'FULL'
            }
        }
    }

    configurations {
        all {
            exclude module: 'commons-logging'
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    viewBinding {
        enabled = true
    }
}

dependencies {
    def support_version = '28.0.0'

    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.kakao.adfit:ads-base:3.11.11'
    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.gms:play-services-base:17.1.0'
    implementation 'com.google.android.gms:play-services-wearable:17.0.0'
    implementation "com.google.android.gms:play-services-ads-identifier:17.0.0"
    implementation "com.google.firebase:firebase-messaging:20.1.6"
    implementation 'com.google.firebase:firebase-analytics:17.4.0'
    implementation 'com.google.firebase:firebase-crashlytics:18.3.1'
    implementation 'com.google.firebase:firebase-perf:19.0.4'

    // butterknife
    def butterknife_version = "10.2.0"
    implementation "com.jakewharton:butterknife:${butterknife_version}"
    kapt "com.jakewharton:butterknife-compiler:${butterknife_version}"

    // dagger
    def dagger_version = "2.37"
    implementation "com.google.dagger:dagger:${dagger_version}"
    implementation "com.google.dagger:dagger-android:${dagger_version}"
    implementation "com.google.dagger:dagger-android-support:${dagger_version}"
    kapt "com.google.dagger:dagger-compiler:${dagger_version}"
    kapt "com.google.dagger:dagger-android-processor:${dagger_version}"

    implementation 'com.squareup:otto:1.3.8'
    implementation 'com.jakewharton.timber:timber:2.5.0'
    implementation 'com.squareup.okhttp3:okhttp:3.9.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.squareup.okhttp:okhttp-urlconnection:2.7.5'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'org.apache.commons:commons-lang3:3.9'
    implementation 'org.apache.httpcomponents:httpmime:4.2.5'
    implementation('org.simpleframework:simple-xml:2.7.1') {
        exclude group: 'stax'
        exclude group: 'xpp3'
    }
    implementation ('org.wordpress:passcodelock:1.5.1') {
        exclude group: 'com.android.support', module: 'preference-v7'
    }
    implementation 'com.nineoldandroids:library:2.4.0'
    implementation 'com.github.flavienlaurent.datetimepicker:library:0.0.2'
    implementation (group: 'com.kakao.sdk', name: 'kakaolink', version: '1.30.4') {
        exclude group: 'com.android.support'
    }
    implementation('de.psdev.licensesdialog:licensesdialog:1.6.0') {
        exclude module: 'support-v4'
    }
    implementation 'com.github.frankiesardo:auto-parcel:0.3.1'
    kapt 'com.github.frankiesardo:auto-parcel-processor:0.3.1'
    implementation 'net.danlew:android.joda:2.11.2'
    implementation 'com.kbeanie:image-chooser-library:1.6.0@aar'
    implementation 'me.dm7.barcodescanner:zxing:1.9.8'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.google.guava:guava:31.1-jre'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    kapt 'com.github.bumptech.glide:compiler:4.11.0'
    implementation 'com.github.esafirm.android-image-picker:imagepicker:2.4.5'
    implementation files('libs/YouTubeAndroidPlayerApi.jar')

    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    kapt 'androidx.lifecycle:lifecycle-common-java8:2.5.1'

    implementation "io.reactivex.rxjava2:rxjava:2.2.12"
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'androidx.exifinterface:exifinterface:1.3.3'

    implementation "com.google.android.exoplayer:exoplayer-core:2.11.3"
    implementation "com.google.android.exoplayer:exoplayer-ui:2.11.3"
    implementation "com.google.android.exoplayer:exoplayer-hls:2.11.3"

    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.19'
    implementation 'androidx.webkit:webkit:1.4.0'

    implementation 'androidx.core:core-ktx:1.3.2'
    kapt "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.5.0"

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // For video converter aar
    implementation 'com.otaliastudios.opengl:egloo:0.4.0'

    /* Coroutines */
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.3.0"
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0"
    implementation 'androidx.fragment:fragment-ktx:1.3.2'
}
```
넵 이렇게 설정되어 있습니다

**Comment by kidoohan** [comment]
@myung6024 님 죄송하지만 가능하실때 줌으로 다시 회의 가능하실까요?

**Comment by myung6024** [comment]
@kidoohan 넵 지금 가능하실까요?

**Comment by kidoohan** [comment]
https://line.zoom.us/j/92553495149?pwd=eGRmbmJ1MWlaNnYyL0tpVXh2NlhTUT09 로 접속 부탁드립니다:)

**Comment by kidoohan** [comment]
![QRcode](https://user-images.githubusercontent.com/15433735/203734860-0a907051-3d7b-4a75-acdb-55625be4e567.png)

**Comment by myung6024** [comment]
@kidoohan 원인 발견하여 해결하였습니다.

**Comment by kidoohan** [comment]
오! 혹시 이슈 원인 공유가능하실까요?

**Comment by myung6024** [comment]
기존에 firebase 플러그인으로 `'com.google.firebase:perf-plugin:1.3.1'`을 사용하였는데 `'com.google.firebase:perf-plugin:1.4.2'`으로 버전을 올린 이후 발생하지 않았습니다.
혹은 빌드 옵션으로
```
        debug {
            FirebasePerformance {
                instrumentationEnabled false
            }
        }
```
를 추가하여 debug 타입에서 firebase performance 플러그인이 작동하지 않도록 설정하면 크래시가 발생하지 않는 것 확인하였습니다.
firebase performance 예전 버전과 어떤 충돌이 있었던 것 같습니다. 어떤 이유인지는 좀 더 확인이 필요합니다.

**Comment by kidoohan** [comment]
firebase 저장소 issue 에서 perf-plugin 이슈로 인한 NoClassDefFoundError 에 대한 것을 보긴 했었는데 이게 firebase 에서만 영향을 줄 것이라고 생각했는데 사이드 이펙트를 주나보네요...

**Comment by myung6024** [comment]
firebase는 정말 상상도 못하고 있어서 dagger와 parcelize까지 전부 변경해보았는데 저 버전 하나만 올리는 것으로 해결이 되더라구요 😭
저 부분이 `모듈(앱 수준) Gradle`이 아닌 `루트 수준(프로젝트 수준) Gradle 파일`의 의존성이라서 더 찾기 힘들었던 것 같습니다.

**Comment by kidoohan** [comment]
그래도 다행이네요 ㅎㅎ 그럼 이슈 닫겠습니다. 확인 감사합니다:)
